services:
  backend:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/housing_platform"
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: housing_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
